# Generated by Django 6.0.6 on 2026-06-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='CountryProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна производитель',
                'verbose_name_plural': 'Страны производители',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип мандарина',
                'verbose_name_plural': 'Типы мандаринов',
            },
        ),
        migrations.CreateModel(
            name='Mandarin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='mandarins/', verbose_name='Изображение')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MandarinchikApp.color', verbose_name='Цвет')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MandarinchikApp.countryproduction', verbose_name='Страна')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MandarinchikApp.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Мандарин',
                'verbose_name_plural': 'Мандарины',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(verbose_name='Оценка')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('mandarin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='MandarinchikApp.mandarin', verbose_name='Мандарин')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
